// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import robot.Constants.DriveTrainConstants;

import com.kauailabs.navx.frc.AHRS;
import edu.wpi.first.wpilibj.SPI;

import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.kinematics.SwerveDriveOdometry;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class drivetrainSubSys extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    private final SwerveModule frontLeft = new SwerveModule(
        DriveTrainConstants.kFrontLeftDriveMotorPort,
        DriveTrainConstants.kFrontLeftTurningMotorPort,
        DriveTrainConstants.kFrontLeftDriveEncoderReversed,
        DriveTrainConstants.kFrontLeftTurningEncoderReversed,
        DriveTrainConstants.kFrontLeftDriveAbsoluteEncoderPort,
        DriveTrainConstants.kFrontLeftDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kFrontLeftDriveAbsoluteEncoderReversed);

    private final SwerveModule frontRight = new SwerveModule(
        DriveTrainConstants.kFrontRightDriveMotorPort,
        DriveTrainConstants.kFrontRightTurningMotorPort,
        DriveTrainConstants.kFrontRightDriveEncoderReversed,
        DriveTrainConstants.kFrontRightTurningEncoderReversed,
        DriveTrainConstants.kFrontRightDriveAbsoluteEncoderPort,
        DriveTrainConstants.kFrontRightDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kFrontRightDriveAbsoluteEncoderReversed);

    private final SwerveModule backLeft = new SwerveModule(
        DriveTrainConstants.kBackLeftDriveMotorPort,
        DriveTrainConstants.kBackLeftTurningMotorPort,
        DriveTrainConstants.kBackLeftDriveEncoderReversed,
        DriveTrainConstants.kBackLeftTurningEncoderReversed,
        DriveTrainConstants.kBackLeftDriveAbsoluteEncoderPort,
        DriveTrainConstants.kBackLeftDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kBackLeftDriveAbsoluteEncoderReversed);

    private final SwerveModule backRight = new SwerveModule(
        DriveTrainConstants.kBackRightDriveMotorPort,
        DriveTrainConstants.kBackRightTurningMotorPort,
        DriveTrainConstants.kBackRightDriveEncoderReversed,
        DriveTrainConstants.kBackRightTurningEncoderReversed,
        DriveTrainConstants.kBackRightDriveAbsoluteEncoderPort,
        DriveTrainConstants.kBackRightDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kBackRightDriveAbsoluteEncoderReversed);

    // Gyro
    private final AHRS gyro = new AHRS(SPI.Port.kMXP);

    // Odometry
    private final SwerveDriveOdometry odometer = new SwerveDriveOdometry( 
        DriveTrainConstants.kDriveKinematics,
        new Rotation2d(0));

    public drivetrainSubSys() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        new Thread(() -> {
            try {
                Thread.sleep(1000);
                zeroHeading();
            } catch (Exception e) {
            }
        }).start();
    }

    @Override
    public void periodic() {
        odometer.update(getGyroHeadingRotation2d(), frontLeft.getState(), frontRight.getState(), backLeft.getState(),
                backRight.getState());
        // Update Smartdash
        SmartDashboard.putNumber("Robot Heading Degrees", getHeadingDegrees());
        SmartDashboard.putNumber("Robot Raw Gyro Heading", gyro.getAngle());
        SmartDashboard.putString("Robot Loc Meters", getPoseMeters().getTranslation().toString());
        SmartDashboard.putNumber("Robot Loc X Ft", Units.metersToFeet(getPoseMeters().getX()));
        SmartDashboard.putNumber("Robot Loc Y Ft", Units.metersToFeet(getPoseMeters().getY()));
        SmartDashboard.putString("Robot Kinematics", DriveTrainConstants.kDriveKinematics.toString());
    }
    
    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void zeroHeading() {
        gyro.reset();
    }

    public double getHeadingDegrees() {
        // This will return values from -180 to +180 degrees of yaw
        return Math.IEEEremainder(gyro.getAngle(), 360);
    }

    public Rotation2d getGyroHeadingRotation2d() {
        // this will return a Rotation2d object of the yaw value -180 to +180 degree
        return Rotation2d.fromDegrees(getHeadingDegrees());
    }

    public Pose2d getPoseMeters() {
        return odometer.getPoseMeters();
    }

    
    public Pose2d getPoseFeet() {
        return odometer.getPoseMeters();
    }

    public void resetOdometry(Pose2d pose) {
        odometer.resetPosition(pose, getGyroHeadingRotation2d());
    }


    public void stopModules() {
        // Should this be done through setModuleStates method ?????
        frontLeft.stop();
        frontRight.stop();
        backLeft.stop();
        backRight.stop();
    }

    public void setModuleStates(SwerveModuleState[] desiredStates) {
        // Make sure all wheels are at the same Velocity (in the "desiredStates" Array)
        SwerveDriveKinematics.desaturateWheelSpeeds(
            desiredStates, 
            DriveTrainConstants.kPhysicalMaxSpeedMetersPerSecond);
        // Send State (Velocity and Angle) to Each Swerve Drive Motor
        frontLeft.setDesiredState(desiredStates[0]);
        frontRight.setDesiredState(desiredStates[1]);
        backLeft.setDesiredState(desiredStates[2]);
        backRight.setDesiredState(desiredStates[3]);
    }
}


